import {test} from 'node:test';import assert from 'node:assert/strict';import {powerLimits,readPowerState,setTransmitPower} from '../reader/power-control.mjs';
function hardware({active=true,fail=false,mismatch=false,mode={type:'CUSTOM',antennas:[1,2],transmitPower:[30,30],query:{session:'S0'},accesses:[{type:'READ',config:{membank:'USER'}}]}}={}){let current=structuredClone(mode),radio=active?'active':'inactive';const calls=[];return {calls,get mode(){return current},get radio(){return radio},async request(path,method,body){calls.push({path,method,body:structuredClone(body)});if(path==='/cloud/region')return {minTxPowerSupported:0,maxTxPowerSupported:300};if(path==='/cloud/status')return {radioActivity:radio};if(path==='/cloud/stop')radio='inactive';if(path==='/cloud/start')radio='active';if(path==='/cloud/mode'){if(method==='PUT'){if(fail&&body.transmitPower[0]!==30)throw Error('HTTP 422');if(!mismatch||body.transmitPower[0]===30)current=structuredClone(body);}return structuredClone(current);}}}}
test('power uses actual regulatory limits and rejects missing or invalid values',()=>{assert.deepEqual(powerLimits({minTxPowerSupported:50,maxTxPowerSupported:300}),{minDbm:5,maxDbm:30});for(const region of [{},{minTxPowerSupported:null,maxTxPowerSupported:300},{minTxPowerSupported:400,maxTxPowerSupported:300},{minTxPowerSupported:0,maxTxPowerSupported:Infinity}])assert.throws(()=>powerLimits(region),/unavailable/)});
test('power change confirms hardware and preserves all mode fields and active state',async()=>{const h=hardware(),original=structuredClone(h.mode);assert.deepEqual(await setTransmitPower(15,h.request,'auth'),{powerDbm:15,verified:true});assert.deepEqual(h.mode,{...original,transmitPower:[15,15]});assert.equal(h.radio,'active');assert.equal((await readPowerState(h.request,'auth')).powerDbm,15)});
test('paused reader remains paused after power change',async()=>{const h=hardware({active:false});await setTransmitPower(20,h.request,'auth');assert.equal(h.radio,'inactive');assert.ok(!h.calls.some(c=>c.path==='/cloud/start'))});
test('out-of-range, fractional and string values never change reader settings',async()=>{for(const value of [-1,31,15.5,'15',null]){const h=hardware();await assert.rejects(setTransmitPower(value,h.request,'auth'),/limits/);assert.ok(!h.calls.some(c=>c.method==='PUT'));}});
test('HTTP rejection and ignored power changes restore original mode without reporting success',async()=>{for(const options of [{fail:true},{mismatch:true}]){const h=hardware(options),original=structuredClone(h.mode);await assert.rejects(setTransmitPower(15,h.request,'auth'),/HTTP 422|did not confirm/);assert.deepEqual(h.mode,original);assert.equal(h.radio,'active')}});
test('power control refuses active tag write mode',async()=>{const h=hardware({mode:{transmitPower:[30],accesses:[{type:'WRITE'}]}});await assert.rejects(setTransmitPower(15,h.request,'auth'),/tag operation/);assert.ok(!h.calls.some(c=>c.method==='PUT'))});
import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import worker from '../worker/index.js';
test('power API requires fresh hardware limits, validates bounds, and claims each request once',async()=>{const db=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+file,'utf8'));const env={WRITE_BRIDGE_TOKEN:'test',DB:{prepare(sql){const stmt=db.prepare(sql);let args=[];return {bind(...v){args=v;return this},async run(){return stmt.run(...args)},async all(){return {results:stmt.all(...args)}}}}}};const post=(path,body)=>worker.fetch(new Request('https://test'+path,{method:'POST',headers:{authorization:'Bearer test','Content-Type':'application/json'},body:JSON.stringify(body)}),env);const get=()=>worker.fetch(new Request('https://test/api/reader/power'),env);try{const command={requestId:'power-test-1234',powerDbm:15};assert.equal((await post('/api/reader/power',command)).status,503);await post('/api/bridge/poll',{readerState:{reading:true,at:new Date().toISOString(),power:{minDbm:0,maxDbm:30,powerDbm:30}}});assert.equal((await (await get()).json()).powerDbm,30);for(const powerDbm of [31,-1,'15',15.5])assert.equal((await post('/api/reader/power',{...command,powerDbm})).status,422);assert.equal((await post('/api/reader/power',command)).status,202);assert.equal((await post('/api/reader/power',command)).status,202);assert.equal((await post('/api/reader/power',{...command,powerDbm:20})).status,409);assert.deepEqual((await (await post('/api/bridge/poll',{})).json()).command,{...command,operation:'power'});assert.equal((await (await post('/api/bridge/poll',{})).json()).command,null);await post('/api/bridge/poll',{readerState:{reading:true,at:new Date(Date.now()-15000).toISOString(),power:{minDbm:0,maxDbm:30,powerDbm:30}}});assert.equal((await (await get()).json()).available,false);assert.equal((await post('/api/reader/power',{...command,requestId:'power-stale-1234'})).status,503);}finally{db.close()}});
